### ISSUE TITLE
Probleme d'affichage en rouge et du logo VIP dans la fiche d'un ticket

### ISSUE THREAD

**Issue by noordo59** [InfotelGLPI/vip#11]
Bonjour,

après avoir installé et activé le plugin, créer un groupe d'utilisateur "VIP", mis l'option VIP sur le groupe à "Oui" et avoir mis un utilisateur dans ce groupe, lorsque je crée un ticket incident ou demande, le nom de l'utilisateur ne s'affiche pas en rouge dans le ticket et le logo "VIP" n"apparait pas a coté du nom.

Cependant, le logo "VIP" apparait bien dans la vue globale de tous les tickets lorsque j'ajoute la colonne "Plugin - VIP".

Pouvez vous m'aider svp?

GLPI v9.4.5
Plugin VIP 1.6.0

**Comment by AliMoonICT** [comment]
Hi,

Same scenario and same result as https://github.com/InfotelGLPI/vip/issues/11#issue-1089833555. Can you please help?

GLPI 9.5.6
Plugin VIP 1.7.2

**Comment by tsmr** [comment]
Please reopen this case into https://github.com/pluginsGLPI/vip if needed . I close this repository
