### ISSUE TITLE
The plugins does not work in version 10.0

### ISSUE THREAD

**Issue by Seranan** [InfotelGLPI/vip#12]
Hello,
The plugin does not work with GLPI version 10.0. Indeed it does not appear in the menu Configuration -> Plugins

**Comment by tsmr** [comment]
Hello
Downloaded from marketplace ? or manually installed ? 

Can you give more informations ? Where si located the files ? Errors en php or sql errors ?

**Comment by Seranan** [comment]
The plugin was installed manually and by putting it in the plugins folder of GLPI.
Here is my approach:

wget https://github.com/InfotelGLPI/vip/archive/refs/tags/1.8.0.tar.gz
tar -xvf 1.8.0.tar.gz

I don't know if I have a php or sql error however I don't see the plugin at the GUI level

**Comment by tsmr** [comment]
please use this link https://github.com/InfotelGLPI/vip/releases/download/1.8.0/glpi-vip-1.8.0.tar.bz2

**Comment by Seranan** [comment]
It's work now, thanks !
