### ISSUE TITLE
Demande d'évolution du plugin VIP

### ISSUE THREAD

**Issue by FD75** [InfotelGLPI/vip#6]
Bonjour,

Nous utilisons ce plugin VIP pour distinguer des catégories de population dans notre ITSM.
Cette distinction ne peut se faire qu'une fois le ticket ouvert or la volumétrie quotidienne de tickets ne permet pas d'isoler rapidement les tickets des VIP. 
L'objectif serait de distinguer dès la page Assistance Tickets les demandes d'intervention des VIP.

Serait-il envisageable que cette distinction en rouge apparaisse depuis l'affichage d'Assistance Tickets afin que le demandeur apparaisse en rouge ?

Bien à vous

**Comment by keha35** [comment]
Bonjour,

Vous pouvez ajouter l'élément "Plugins - VIP" dans le tableau des tickets cela ne suffit-il pas? 
![image](https://user-images.githubusercontent.com/39367117/89387232-7de09c80-d702-11ea-99ee-ca2e10366984.png)
